[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/sabai-rs/sabai"

[workspace.dependencies]
sabai-core = { path = "crates/sabai-core", version = "0.0.0" }
sabai-macros = { path = "crates/sabai-macros", version = "0.0.0" }
sabai-http = { path = "crates/sabai-http", version = "0.0.0" }
sabai-orm = { path = "crates/sabai-orm", version = "0.0.0" }
sabai-auth = { path = "crates/sabai-auth", version = "0.0.0" }
sabai-queue = { path = "crates/sabai-queue", version = "0.0.0" }

bytes = "1"
dotenvy = "0.15"
http = "1"
http-body = "1"
pollster = "0.4"
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
serde = "1"
serde_json = "1"
syn = { version = "2", default-features = false, features = ["derive", "parsing", "printing", "proc-macro"] }
toml = { version = "0.9", default-features = false, features = ["std", "parse", "serde"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "fmt", "ansi"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "warn"

[profile.dev]
debug = "line-tables-only"
