[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/sabai-rs/sabai"

[workspace.dependencies]
sabai-core = { path = "crates/sabai-core", version = "0.0.0" }
sabai-macros = { path = "crates/sabai-macros", version = "0.0.0" }
sabai-http = { path = "crates/sabai-http", version = "0.0.0" }
sabai-orm = { path = "crates/sabai-orm", version = "0.0.0" }
sabai-auth = { path = "crates/sabai-auth", version = "0.0.0" }
sabai-queue = { path = "crates/sabai-queue", version = "0.0.0" }

http = "1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "warn"

[profile.dev]
debug = "line-tables-only"

[profile.dev.build-override]
opt-level = 3
